<a href="https://colab.research.google.com/github/asadibrahim206/Mechine-Learning-projects/blob/main/movies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [19]:
df = pd.read_csv("sample_data/movies_metadata.csv", engine='python', on_bad_lines='skip')

In [20]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173

In [21]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [22]:
df.info

<bound method DataFrame.info of       adult                              belongs_to_collection    budget  \
0     False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
1     False                                                NaN  65000000
2     False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
3     False                                                NaN  16000000
4     False  {'id': 96871, 'name': 'Father of the Bride Col...         0
...     ...                                                ...       ...
3807  False                                                NaN         0
3808  False  {'id': 259401, 'name': 'The Invisible Man (Uni...    328000
3809  False                                                NaN         0
3810  False                                                NaN         0
3811  False                                                NaN   1500000

                                                 genres  \
0     [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1     [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2     [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                        [{'id': 35, 'name': 'Comedy'}]
...                                                 ...
3807  [{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...
3808  [{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...
3809  [{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...
3810           [{'id': 878, 'name': 'Science Fiction'}]
3811  [{'id': 10402, 'name': 'Music'}, {'id': 27, 'n...

                                  homepage     id    imdb_id  \
0     http://toystory.disney.com/toy-story    862  tt0114709
1                                      NaN   8844  tt0113497
2                                      NaN  15602  tt0113228
3                                      NaN  31357  tt0114885
4                                      NaN  11862  tt0113041
...                                    ...    ...        ...
3807                                   NaN  34077  tt0052846
3808                                   NaN  10787  tt0024184
3809                                   NaN  43109  tt0052969
3810                                   NaN  43230  tt0050610
3811                                   NaN  15855  tt0036261

     original_language               original_title  \
0                   en                    Toy Story
1                   en                      Jumanji
2                   en             Grumpier Old Men
3                   en            Waiting to Exhale
4                   en  Father of the Bride Part II
...                ...                          ...
3807                en       The Giant Gila Monster
3808                en            The Invisible Man
3809                en            The Killer Shrews
3810                en                       Kronos
3811                en         Phantom of the Opera

                                               overview  ...  release_date  \
0     Led by Woody, Andy's toys live happily in his ...  ...    1995-10-30
1     When siblings Judy and Peter discover an encha...  ...    1995-12-15
2     A family wedding reignites the ancient feud be...  ...    1995-12-22
3     Cheated on, mistreated and stepped on, the wom...  ...    1995-12-22
4     Just when George Banks has recovered from his ...  ...    1995-02-10
...                                                 ...  ...           ...
3807  A small town in Texas finds itself under attac...  ...    1959-06-25
3808  Working in Dr. Cranley's laboratory, scientist...  ...    1933-11-13
3809  Trapped on a remote island by a hurricane, a g...  ...    1959-06-25
3810  Scientists investigate what appears to be a me...  ...    1957-03-31
3811  Pit violinist Claudin hopelessly loves rising ...  ...    1943-08-27

        revenue runtime                                   spoken_languages  \
0     373554033    81.0           [{'iso_639_1': 'en', 'name': 'English'}]
1     262797249   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2             0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]
3      81452156   127.0           [{'iso_639_1': 'en', 'name': 'English'}]
4      76578911   106.0           [{'iso_639_1': 'en', 'name': 'English'}]
...         ...     ...                                                ...
3807          0    74.0           [{'iso_639_1': 'en', 'name': 'English'}]
3808          0    71.0           [{'iso_639_1': 'en', 'name': 'English'}]
3809          0    69.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
3810          0    78.0           [{'iso_639_1': 'en', 'name': 'English'}]
3811          0    92.0           [{'iso_639_1': 'en', 'name': 'English'}]

        status                                            tagline  \
0     Released                                                NaN
1     Released          Roll the dice and unleash the excitement!
2     Released  Still Yelling. Still Fighting. Still Ready for...
3     Released  Friends are the people who let you be yourself...
4     Released  Just When His World Is Back To Normal... He's ...
...        ...                                                ...
3807  Released                                                NaN
3808  Released  CARL LAEMMLE presents H.G. WELLS' FANTASTIC SE...
3809  Released       All that was left after...THE KILLER SHREWS!
3810  Released                          World-Destroying Monster!
3811  Released                    The screen's classic of terror!

                            title  video vote_average vote_count
0                       Toy Story  False          7.7       5415
1                         Jumanji  False          6.9       2413
2                Grumpier Old Men  False          6.5         92
3               Waiting to Exhale  False          6.1         34
4     Father of the Bride Part II  False          5.7        173
...                           ...    ...          ...        ...
3807       The Giant Gila Monster  False          4.2         12
3808            The Invisible Man  False          7.3        151
3809            The Killer Shrews  False          4.3         18
3810                       Kronos  False          5.8          8
3811         Phantom of the Opera  False          5.6         30

[3812 rows x 24 columns]>

In [23]:
df.shape

(3812, 24)

In [24]:
df.isnull().sum()

adult                       0
belongs_to_collection    3150
budget                      0
genres                      0
homepage                 3574
id                          0
imdb_id                     0
original_language           0
original_title              0
overview                   18
popularity                  0
poster_path                18
production_companies        0
production_countries        0
release_date                4
revenue                     0
runtime                     6
spoken_languages            0
status                      5
tagline                   929
title                       0
video                       0
vote_average                0
vote_count                  0
dtype: int64

In [25]:
df = df.drop_duplicates().reset_index(drop = True)

In [26]:
df = df[['title', 'overview', 'genres', 'tagline', 'vote_average', 'popularity']]

In [27]:
df = df.dropna(subset=['title'])

In [28]:
df['overview'] = df['overview'].fillna('')

In [29]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [30]:
import ast
df['genres']=df['genres'].apply(lambda x :" ".join([i['name']for i in ast.literal_eval(x)]))

In [31]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.712900
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [32]:
df['tagline'] = df['tagline'].fillna('')

In [33]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [34]:
df['tags'] = df['overview']+ " " + df['genres']+ " " + df['tagline']

In [35]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.712900,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

#Using NLP

In [36]:
df['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

In [37]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [38]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [39]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [40]:
def preprocess_text(text):
  #Lower Case
  text =  str(text).lower()
  #Remove Punctuations
  text = re.sub(r'[^a-z\s]', '', text)
  words = text.split()
  #remove Stopwords
  words = [word for word in words if word not in stop_words]
  #Lemmatize
  words = [lemmatizer.lemmatize(word) for word in words ]

  return " ".join(words)

In [41]:
df['tags'] = df['tags'].apply(preprocess_text)

In [42]:
df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [43]:
df = df.reset_index(drop = True)

In [44]:
indices = pd.Series(df.index, index = df ['title']).drop_duplicates()
indices

title
Toy Story                         0
Jumanji                           1
Grumpier Old Men                  2
Waiting to Exhale                 3
Father of the Bride Part II       4
                               ...
The Giant Gila Monster         3806
The Invisible Man              3807
The Killer Shrews              3808
Kronos                         3809
Phantom of the Opera           3810
Length: 3811, dtype: int64

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [46]:
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words="english")

In [47]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [48]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 165317 stored elements and shape (3811, 50000)>